name: Run Node.js Tests

on:
  push:
    paths:
      - 'jest-supertest/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Change Directory
        run: cd jest-supertest
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
