name: Run Node.js Tests

on:
  push:
    paths:
      - 'jest-supertest/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jest-supertest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
